port: 8080
base_url: /

auth: # details for nginx basic auth to put in the urls on the index page. exclude this section if you don't want to use basic auth
    username: # Your username here
    password: # Your password here

feeds:
    feed_1:
        name: # Your feed name here
        processor: # Your processor script here
        url: # Your feed URL here
        args: # Additional arguments for the processor
            arg1: # ...

    type_1:
        feed_2:
            name: # Your feed name here
            processor: # Your processor script here
            url: # Your feed URL here
            args: # Additional arguments for the processor, optional
                arg1: # ...

    type_2:
        feed_3:
            name: # Your feed name here
            processor: # Your processor script here
            url: # Your feed URL here